name: Promote API

on:
  workflow_dispatch:
    inputs:
      api:
        description: "Path to the API folder"
        type: choice
        required: true
        options:
          - "flights"
          - "routes"
      environment:
        description: "Environment to deploy to"
        type: choice
        default: "dev"
        options:
          - "dev"
          - "tst"
          - "acc"
          - "prd"

env:
  TEAM_NAME: flight-data # This should altimately be retrieved from the repo metadata
  API_FOLDER: ${{ github.workspace }}/apis/${{ inputs.api }}
  SYSTEM_ACCOUNT: sa-flight-data-cp-admin

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare Config
    outputs:
      system_account_token: ${{ steps.set-output.outputs.SYSTEM_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import system account Token from Vault
        id: import-token
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/system-accounts/${{ env.SYSTEM_ACCOUNT }} token | SYSTEM_ACCOUNT_TOKEN ;
      
      - name: Setup Output variables
        id: set-output
        run: |
          echo "SYSTEM_ACCOUNT_TOKEN=${{ steps.import-token.outputs.SYSTEM_ACCOUNT_TOKEN }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    name: Build Config
    needs: prepare
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Config
        id: build
        uses: ./platform-actions/build-kong-config
        with:
          environment: ${{ inputs.environment }}
          api_folder: ${{ env.API_FOLDER }}
          konnect_token: ${{ needs.prepare.outputs.system_account_token }}

  deploy:
      name: Deploy Config
      runs-on: ubuntu-latest
      needs: 
        - build
        - prepare
      environment: ${{ inputs.environment }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - uses: ./platform-actions/apply-kong-config
          with:
            environment: ${{ inputs.environment }}
            api_folder: ${{ env.API_FOLDER }}
            konnect_token: ${{ needs.prepare.outputs.system_account_token }}
            client_id: ${{ secrets.OIDC_CLIENT_ID }}
            client_secret: ${{ secrets.OIDC_CLIENT_SECRET }}
